# Generated by Django 2.0.1 on 2018-01-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, help_text='product name', max_length=200, null=True)),
                ('product_details', models.TextField(blank=True, help_text='product details', null=True)),
                ('price', models.IntegerField()),
                ('active', models.IntegerField(default=1)),
            ],
        ),
    ]
